### PR TITLE
add option to zoom in, out and reset

### LINKED ISSUE #356: Enable/Allow to zoom in/out
Since the WB is backed by a web browser, I would expect to be able to zoom in and out (Ctrl+ and Ctrl- typically) and this is not enabled. It would be great if it were

### PR DESCRIPTION
**Pull request by vsvipul**
fixes #356.
Used
Ctrl + = for zoom in 
Ctrl + - for zoom out
Ctrl + 0 for zoom reset

### CODE REVIEW

**Comment by vsvipul** [comment]
why is the travis build failing in the last step? can someone help me figure it out?

**Comment by majurg** [comment]
@vsvipul I think that build failure may just be a fluke, I will restart the and see.

**Comment by majurg** [comment]
@vsvipul From what I can tell, I think the Travis CI errors are because the PR was opened from a fork. We can disregard the build failures for now I think.

**Comment by vsvipul** [comment]
@majurg i have made the required changes. Thanks. :)

**Pull request merged**
